server:
  port: 8180

spring:
  cloud:
    config:
      enabled: false
  application:
    name: stackover-auth-service
  profiles:
    active: dev # профиль по умолчанию
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        order_inserts: true
        enable_lazy_load_no_trans: true
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        jdbc:
          lob:
            non_contextual_creation: true
          batch_size: 20
        generate_statistics: false
    show-sql: true
    database: postgresql
  datasource:
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.xml

feign:
  circuitbreaker:
    enabled: true
    client:
      config:
        default:
          errorDecoder: stackover.auth.service.feign.CustomErrorDecoder

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: ${spring.application.name}  # Используем имя приложения как hostname
    preferIpAddress: false
    instance-id: ${spring.application.name}:${server.port}

# Добавленные JWT-настройки
jwt:
  secret: RFa4dus-HnNCQ71rIJPFo1HJHl7qWSQuO3cyRE1elssv0Yct9KWUUz7lNiXLZrcbXWiEVLtZtqWqjil71vIwfw # Секретный ключ (минимум 256 бит)
  expiration-ms: 86400000 # 24 часа в миллисекундах
  refresh-expiration-ms: 2592000000 # 30 дней в миллисекундах

security:
  ignored:
    - /swagger-ui/**
    - /v3/api-docs/**
    - /actuator/health

logging:
  level:
    org.springframework.core.env: TRACE
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    stackover.resource.service: TRACE


    # Добавьте эти новые настройки
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.stat: DEBUG
    org.hibernate.engine.jdbc.spi.SqlStatementLogger: DEBUG
    org.springframework.transaction: DEBUG
    org.springframework.orm.jpa: DEBUG

