server:
  port: 8761

spring:
  application:
    name: stackover-eureka-server

eureka:
  server:
    expected-client-renewal-interval-seconds: 30  # Даём запас на задержки
    renewal-percent-threshold: 0.49  # Более агрессивная очистка
    eviction-interval-timer-in-ms: 5000  # Проверка каждые 5 сек (вместо 60)
    enable-self-preservation: false  # Отключаем self-preservation (для dev-среды)
    response-cache-update-interval-ms: 5000  # Чаще обновлять кеш
    peer-node-read-timeout-ms: 10000  # На всякий случай, если появится репликация
    peer-node-connect-timeout-ms: 5000

  instance:
    lease-renewal-interval-in-seconds: 10  # Клиенты шлют heartbeat чаще
    lease-expiration-duration-in-seconds: 30

  client:
    register-with-eureka: false  # Сервер не регистрирует себя
    fetch-registry: false        # Сервер не получает реестр
    service-url:
      defaultZone: http://localhost:8761/eureka